# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 2.7
    gaps_out = 7.8
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 6

    # Make active windows slightly transparent
    active_opacity = 0.98

    # Make unfocused windows even more transparent
    inactive_opacity = 0.92

    # Make screen color more vivid
    screen_shader = ~/.config/hypr/shaders/vibrance.frag

}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
